version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi-application
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mongodb


  mongodb:
    container_name: ${DB_HOST}
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /mongodb-data:/data/initiate_data
      - ./initiate_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - .env
    command: [ --auth ]

